### ISSUE TITLE
Can't create collection1 core after https://github.com/IQSS/dataverse/pull/6146 was merged

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#102]
Ever since https://github.com/IQSS/dataverse/pull/6146 was merged we can't use ec2-create-instance.sh on the develop branch. We get this error:

TASK [dataverse : create collection1 core] *************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/solr/bin/solr create_core -c collection1 -d /usr/local/solr/server/solr/collection1/conf/", "delta": "0:00:01.261084", "end": "2019-09-17 19:49:25.041379", "msg": "non-zero return code", "rc": 1, "start": "2019-09-17 19:49:23.780295", "stderr": "\nERROR: Unable to delete directory /usr/local/solr/server/solr/collection1.", "stderr_lines": ["", "ERROR: Unable to delete directory /usr/local/solr/server/solr/collection1."], "stdout": "", "stdout_lines": []}
 [WARNING]: Unable to use /home/solr/.ansible/tmp as temporary directory,
failing back to system: [Errno 13] Permission denied: '/home/solr'
	to retry, use: --limit @/home/centos/dataverse/dataverse.retry

PLAY RECAP *********************************************************************
localhost                  : ok=76   changed=57   unreachable=0    failed=1   

@landreev created a branch at https://github.com/IQSS/dataverse-ansible/compare/dataverse-6142-solr-schema-changes

@donsizemore can you please take a look at the branch to see what we're up to? Thanks!

**Comment by landreev** [comment]
@donsizemore - this is happening because the schema was split into 3 files; so 2 more files need to be installed. 
In the branch mentioned above, the file tasks/dataverse-solr.yml has the extra lines for this. 
I was going to make a PR for this shortly; but not from this branch - it has some other, experimental stuff that I've been playing with, that doesn't need to be in the master branch.

**Comment by poikilotherm** [comment]
Happy to answer any questions or change code if necessary. :smile:

**Comment by donsizemore** [comment]
@pdurbin try the branch now?

`$ ec2/ec2-create-instance.sh -b develop -a dataverse-6142-solr-schema-changes -r https://github.com/IQSS/dataverse.git`

**Comment by pdurbin** [comment]
Fixed by pull request #104! Thanks, @donsizemore ! Closing.
