### ISSUE TITLE
CentOS 8 support

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#111]
CentOS 8 is out! 🎉 

ec2-create-instance.sh currently uses ami-9887c6e7, which is CentOS 7. We should probably add a flag to be able to choose between AMI images (but still have a sane default, like the CentOS 7 AMI we're using now).

From http://irclog.iq.harvard.edu/dataverse/2019-09-26#i_107133 @donsizemore indicates that we're waiting for EPEL to catch up on some R dependencies.

If we want to small chunk this issue with an AMI pull request (including a note in the README about R stuff not working on on CentOS 8) followed by another (to remove the R note once EPEL is ready), that's fine.

**Comment by donsizemore** [comment]
i'll give them a day or two to respond to https://pagure.io/epel/issue/78

**Comment by donsizemore** [comment]
Now dying without python-psycopg2

**Comment by pdurbin** [comment]
> Now dying without python-psycopg2

Interesting. Which RPM depends on that?

**Comment by donsizemore** [comment]
@pdurbin it's provided by the Postgres repo, and as of this writing there are PostgresQL RPMs for RHEL8 but not CentOS8 https://yum.postgresql.org/repopackages.php

**Comment by pdurbin** [comment]
I see. Can we use whatever version of Postgres that ships with CentOS 8? I assume it isn't the exact version we say Dataverse wants ("Version 9.6 is strongly recommended because it is the version developers and QA test with").

**Comment by donsizemore** [comment]
made it to
`ImportError: /usr/lib64/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PQencryptPasswordConn`

**Comment by pdurbin** [comment]
I just thought I'd mention that I listened to the first part of https://linuxunplugged.com/320 and there's a new thing called "CentOS Stream" that may be of interest. From the show notes:

"CentOS Stream — CentOS Stream will be a rolling-release Linux distro that exists as a midstream between the upstream development in Fedora Linux and the downstream development for Red Hat Enterprise Linux (RHEL). It is a cleared-path to contributing into future minor releases of RHEL while interacting with Red Hat and other open source developers. This pairs nicely with the existing contribution path in Fedora for future major releases of RHEL."

**Comment by donsizemore** [comment]
@pdurbin the only suitable CentOS 8 AMI I find in AWS at the moment is "CentOS 8 Minimal Latest" aka ami-034a46a96c820cc75. To test in IQSS space:

```An error occurred (OptInRequired) when calling the RunInstances operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=ef6kit54bxdxm5ec5h7921duf```

Could you or @djbrooke accept terms and subscribe? (or I can wait for the community image)

**Comment by pdurbin** [comment]
@donsizemore let's wait for the community image.

Also, I saw some chatter at https://github.com/irvingpop/packer-chef-highperf-centos-ami/pull/9 and I know we talked about that image at http://irclog.iq.harvard.edu/dataverse/2019-10-03#i_107997 but I can't remember the current status of testing it.

**Comment by donsizemore** [comment]
@pdurbin we're good with CentOS 8 as long as we use Postgres 10: https://github.com/IQSS/dataverse-ansible/commit/3d87b8f77ca207e1abd1e0a9a0bc56cae971709b

**Comment by donsizemore** [comment]
CentOS released AWS images, so I've made CentOS 8 the default in EC2 and an Vagrant.
