### ISSUE TITLE
no action detected in task: create grafana datasource

### ISSUE THREAD

**Issue by thu07** [IQSS/dataverse-ansible#122]
Hi

I'm new to Ansible. When I follow the steps to install Dataverse-ansible, I met the problem with 'grafana datasource creation' as follows:

[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The
 module documentation details page may explain more about this rationale.. This feature will be 
removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/osboxes/dataverse/tasks/grafana.yml': line 68, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: create grafana datasource
  ^ here

![image](https://user-images.githubusercontent.com/40651520/66215041-c8336000-e690-11e9-8c20-d91d297dde95.png)
![image](https://user-images.githubusercontent.com/40651520/66215211-1cd6db00-e691-11e9-959e-15a9bf3eb1fa.png)

**Comment by donsizemore** [comment]
I don't get this in current master (on CentOS 7):

`
TASK [dataverse : create grafana datasource] ***********************************
changed: [default] => {"changed": true, "id": 1, "msg": "Datasource prometheus created : Datasource added", "name": "prometheus"}
`

How are you launching Ansible (version, platform, etc)?

Full disclosure: I'm only using default values.

**Comment by thu07** [comment]
Hi Don

Thanks for your reply. I installed the Dataverse-ansible on Centos 7 in the Virtualbox 6.0. The Ansible version is 2.4.2.0 . I use the default values as well.

**Comment by donsizemore** [comment]
That may be the difference: my CentOS 7 box picks up ansible-2.8.5.

2.4 may not include the grafana_datasource module.

**Comment by thu07** [comment]
Yeah. That's maybe the problem. I will update the ansible and try again. Thanks.

**Comment by thu07** [comment]
It works. Thank you.
