### ISSUE TITLE
EC2: support grab_logs option

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-ansible#123]
for benefit of jenkins

**Comment by donsizemore** [comment]
@pdurbin hmmph. it's in the rsync 3.1.3 man page on my mac (also running 10.14.6) but I tested on Ubuntu 18.04 / rsync 3.1.2. i'm not even certain we need that option.

**Comment by donsizemore** [comment]
works as advertised - closing.

**Comment by pdurbin** [comment]
Today I documented this in https://github.com/IQSS/dataverse/pull/6344
