### ISSUE TITLE
support new Python 3 installer (formerly in Perl)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#139]
@donsizemore this is the new branch I mentioned today: https://github.com/IQSS/dataverse/tree/3937-rewrite-installer-in-python-again

Here's the "Rewrite installer in Python 3" issue in the main repo: https://github.com/IQSS/dataverse/issues/3937

If would help us gain confidence in the new Python 3 installer if we could exercise it with our spin up scripts.

**Comment by donsizemore** [comment]
At present we do most of the stuff the install script _would_ do in Ansible tasks, then call glassfish-setup directly: https://github.com/IQSS/dataverse-ansible/blob/master/tasks/dataverse-install.yml

If you want to stick with the included script I can pick up the default.config bit; @pameyer his wanted that for a long time.

**Comment by pdurbin** [comment]
@donsizemore ah, good point. Using the new script could be a way to address this issue:

- consider using non-interactive (default.config) dataverse installer? #15

**Comment by donsizemore** [comment]
I pushed what I have so far https://github.com/IQSS/dataverse-ansible/tree/139_python3_installer but ran into the below. This is in python-3.6.8 on CentOS 7.

install.py\", line 130\n    print \"\\nThis appears to be a MacOS X system; good.\"\n                                                       ^\nSyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"\\nThis appears to be a MacOS X system)?\n", "stderr_lines": ["  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1577117159.18-158957952228512/install.py\", line 130", "    print \"\\nThis appears to be a MacOS X system; good.\"", "                                                       ^", "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"\\nThis appears to be a MacOS X system)?"]
