### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by danschmidt5189** [IQSS/dataverse-ansible#14]
We should integrate CI so that changes are automatically tested. At minimum, I would want to verify that a first-run completes successfully using Ansible 1.9 against a CentOS 7 target. Afterwards, we could add more Ansible versions (e.g. 2.4, which is what my team uses).

Does anyone have a CI preference? [Travis CI](https://travis-ci.org) is free for open-source projects, easy to setup, and happens to be what ansible-galaxy scaffolds by default.

Note that this will require admin rights on the repository (to configure the webhook) as well as an account on the relevant CI platform. I'm happy to demo these on my fork for now (danschmidt5189/dataverse-ansible), but think it would be better to integrate them into the main repository.

**Comment by pdurbin** [comment]
I'll defer to @donsizemore on this but I'd be completely fine with Travis. Over at https://github.com/IQSS/dataverse-puppet/issues/10 I made some noise about how we started using Travis for the Dataverse project itself (building the Java project and running tests). If there's anything you need from me, permission-wise, please just let me know.

**Comment by pdurbin** [comment]
@danschmidt5189 I've been chatting with @donsizemore about this and we'd love for you to move forward (you can find us in #dataverse on freenode). I just added this issue to the "Dev Efforts by the Dataverse Community" spreadsheet at https://docs.google.com/spreadsheets/d/1pl9U0_CtWQ3oz6ZllvSHeyB0EG1M_vZEC_aZ7hREnhE/edit?usp=sharing . Thanks!

**Comment by djbrooke** [comment]
Hey @danschmidt5189 - thanks for working on this. If you don't mind letting us know, are you working on setting up a new Dataverse installation or working with a current one? If it's a new installation, please let us know when/if you're ready to be put on the map at dataverse.org!

**Comment by danschmidt5189** [comment]
We're setting up a new instance. Still in the early stages, though — nothing worth showing off just yet, but I'll ping you all once it's up and pretty.

RE: Travis — I'll take a stab at it on my fork over the weekend. I don't think I'll need any permissions; you all will just have to set up Travis for the main project once the PR goes in.

**Comment by pdurbin** [comment]
@danschmidt5189 sounds good. If we don't notice the pull request right away, please just ping us. Thanks for working on this!

**Comment by pdurbin** [comment]
@danschmidt5189 thanks for making pull request #16 which was just merged.

The build failed: https://travis-ci.org/IQSS/dataverse-ansible/builds/352498390

There's an error that says, "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

So maybe we need to speed it up or something? Any thoughts?

The line before it failed said `TASK [dataverse : install Shibboleth RPMs for RedHat/CentOS7] ******************` and @pameyer warned us about timeouts at https://github.com/IQSS/dataverse-ansible/pull/16#issuecomment-370287639 and so did you in the pull request description. Should we disable the shib stuff? @donsizemore does use Shib.

**Comment by donsizemore** [comment]
I do use Shibboleth but only on two production boxes. Shibboleth configuration is highly site-specific and their repo mirrors are notorious for going AWOL. I offered to set up a Shib mirror on ibiblio, but... I forget why they didn't want to. Wouldn't hurt my feelings in the least to comment out the Shib stuff.

**Comment by pameyer** [comment]
Would it be worth doing conditionally (aka - using an ansible variable / when statements for the shib stuff)?

**Comment by danschmidt5189** [comment]
IMO we could just make it conditional, e.g.:

```
- include_tasks: dataverse-shibboleth.yml
  when: dataverse.shibboleth.enabled | bool and …
```

Ideally, much of what the role currently does (Postgres, Solr, Shib, …) would be extracted into separate roles or delegated to existing Ansible Galaxy roles. This role's core concern is actually quite small — just running the installer and running some configurations.

And FWIW, in the long-run I would be looking to deploy this on Kubernetes/Docker Swarm. Build/run is a much easier paradigm than what is essentially a script-based approach used by all major CM tools (Ansible, Chef, …). Maybe you've already done that? My apologies for not having looked into it — our infrastructure is still catching up, and sadly we're mostly stuck in Ansible-land for now. 😅

**Comment by donsizemore** [comment]
we do, it just defaults to on:

`  shibboleth:
    enabled: true
    repo: "http://download.opensuse.org/repositories/security:/shibboleth/CentOS_7/security:shibboleth.repo"
`

**Comment by danschmidt5189** [comment]
@donsizemore Yeah, but that setting doesn't control whether the shib repo/rpms are installed. It only factors into the [post-install](https://github.com/IQSS/dataverse-ansible/search?utf8=✓&q=dataverse.shibboleth.enabled&type=) step.

**Comment by pdurbin** [comment]
I was just mentioning this effort over at http://irclog.iq.harvard.edu/dataverse/2018-03-22#i_64908 and it reminded me to check in to see if there's anything you need from me.

**Comment by pdurbin** [comment]
@donsizemore disable shib by default in f884e34 and now Travis is passing: https://travis-ci.org/IQSS/dataverse-ansible/builds/362264286

Great work @danschmidt5189 and @donsizemore ! It's safe to close this issue, right?

**Comment by pdurbin** [comment]
Now that we have Travis CI confirming that the code is working (thanks again @danschmidt5189 !) Maybe we should add a "build status" button to the README. I just made pull request #18 to add it.

I copied the Markdown from https://travis-ci.org/IQSS/dataverse-ansible like this:

![screen shot 2018-04-11 at 9 14 58 am](https://user-images.githubusercontent.com/21006/38619015-32a52fe0-3d69-11e8-8ac6-b2f7a6ec65fd.png)
