### ISSUE TITLE
ability to spin up new S3 options in pull request 6490 upstream

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#140]
https://github.com/IQSS/dataverse/pull/6490 has a load of new options for S3. It would be nice to have all the config flags (to be finalized!) to be able to spin it up.

**Comment by donsizemore** [comment]
I see:

- [ ] < id > for storage identifier
- [ ] dataverse.files.< id >.upload-redirect=true
- [ ] dataverse.files.< id >.download-redirect=true
- [ ] dataverse.files.< id >.upload-redirect=true
- [ ] echo `aws s3api put-bucket-cors --bucket < BUCKET_NAME > --cors-configuration file://cors.json` at end of run when direct download enabled to allow direct download for previewers
- [ ] dataverse.files.< id >.ingestsizelimit
- [ ] dataverse.files.< id >.url-expiration-minutes
- [ ] MaxFileUploadSizeInBytes

@qqmyers have I missed anything?

**Comment by qqmyers** [comment]
I think that's all for AWS S3 except 
dataverse.files.\<id\>.bucket-name
dataverse.files.\<id\>.type
dataverse.files.\<id\>.label

There are other options to use a custom URL, use a proxy, etc. but nothing needed for AWS S3

Also fyi: you've got 2 and 4 as duplicates in the list above.

For CORS, you can probably just use '*' for the hosts, but that could be locked to the instance you spin up and any previewer host too.

**Comment by qqmyers** [comment]
Also dataverse.files.storage-driver-id=\<id\> to make your driver the default
