### ISSUE TITLE
consider using non-interactive (default.config) dataverse installer?

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse-ansible#15]
Would it be worth changing the dataverse installation tasks to use the non-interactive mode in the dataverse installer (rather than doing glassfish/postgres/post-install separately)?

**Comment by pameyer** [comment]
Not with the current state of the dataverse installer; in particular the assumption that the install script has administrative access to the postgresql database.  Might be possible with `--pg_only`, but not sure how the non-interactive installation mode would interact with postgres only mode.

**Comment by jmjamison** [comment]
I am trying both.  Though for work a scripted install is required. Working through the problems with manual installs has helped to try and work out the script install.

**Comment by donsizemore** [comment]
@pameyer dataverse-ansible is really just a wrapper for the Dataverse installer. The postgres portion is idempotent; the glassfish portion... is not, but the installer itself will only install on a "clean" database.

I can absolutely add flags for these options, but given the heterogeneity of the Dataverse upgrade process, I don't see the benefit of idempotence (yet). I did tinker with default.config but, running a shell script wrapped in a Python script over SSH, ran into parsing trouble. In the ansible world anything that would normally be passed in default.config would be specified in group_vars.

I'm not saying no, I just... where to start?

**Comment by jmjamison** [comment]
This was last year. Ultimately the ansible script worked quite well.  Many (if not most) of the problems were do to my inexperience.

**Comment by pdurbin** [comment]
> In the ansible world anything that would normally be passed in default.config would be specified in group_vars.

I use the group vars stuff all the time and it's fantastic. If you haven't tried them, please see https://github.com/IQSS/dataverse-ansible/tree/38b01ace93b639a0df5278bcf9c921a3988113a2#configuration

**Comment by pameyer** [comment]
@donsizemore I'm perfectly ok with "no" (especially with the postgres / admin access bits).  That said, I've had reasonably luck making the non-interactive installer idempotent by making the ansible shell action conditional on the absence of a logfile.

**Comment by pdurbin** [comment]
https://github.com/IQSS/dataverse/issues/3937 is in the current sprint and is about rewriting the Perl "install" script into Python so I'm closing this. We can discuss there.
