### ISSUE TITLE
update prometheus configs for payara

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-ansible#154]
- [x] move API test suite
- [x] correct prometheus.yml
- [x] enable jmx_exporter agent

**Comment by donsizemore** [comment]
@pdurbin we now have the default Payara metrics https://payara5.odum.unc.edu/metrics talking to Prometheus https://payara5.odum.unc.edu/prometheus/graph?g0.range_input=1h&g0.expr=base_memory_usedHeap_bytes&g0.tab=0 via the jmx_exporter agent.

The above links are to Odum's test box but the role can also spin up Prometheus in EC2 on any repo/branch, and in particular launches Prometheus prior to its running the API test suite so one may watch basic JVM effects of the test suite (or any other Dataverse task) in real-time.

Guidance on a desired Grafana dashboard welcomed.

**Comment by pdurbin** [comment]
@donsizemore that's awesome! 🎉
