### ISSUE TITLE
incorrect jvm options for direct up/downloads

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse-ansible#168]
So much for reviewing...

in tasks/s3.yml jvm options are set for 
-Ddataverse.files.s3.direct-download
and
-Ddataverse.files.s3.direct-upload, but the real options are
-Ddataverse.files.s3.download-redirect
and
-Ddataverse.files.s3.upload-redirect

Without the correct options set, direct upload and download do not get used.

**Comment by donsizemore** [comment]
@qqmyers well, I thought I had created a branch, but I just pushed the fix to master (sorry).

How 'bout now?

**Comment by qqmyers** [comment]
Looks good - thanks!
