### ISSUE TITLE
use solr 7

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-ansible#17]
in preparation for the 4.9 release

**Comment by pdurbin** [comment]
@donsizemore thanks for jumping this. If you want a preview of the instructions that will appear for Solr in the Dataverse Installation Guide, you can look at https://github.com/IQSS/dataverse/blob/a088d5efc269d9c56b6fcbe6c2a6b39335480d6a/doc/sphinx-guides/source/installation/prerequisites.rst#solr

I don't **think** these are going to change but I can try to remember to ping you if they do.

**Comment by pdurbin** [comment]
@donsizemore heads up that Dataverse just upgraded to 7.3.0 ("develop" branch): https://github.com/IQSS/dataverse/pull/4621

**Comment by pdurbin** [comment]
Dataverse 4.9 is out: https://github.com/IQSS/dataverse/releases/tag/v4.9
