### ISSUE TITLE
unable to upload files

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse-ansible#20]
I've run the install on aws and vagrant.  Now that I have the AWS machine size corrected the install runs to completion.

One problem I am having both with vagrant and aws is that I'm unable to upload files.  Out-of-the-box the directory is /usr/local/dvn/data.

These are the jvm options:
<jvm-options>-Ddataverse.files.directory=/usr/local/dvn/data</jvm-options>
        <jvm-options>-Ddataverse.rserve.host=rserve.ec2-54-219-54-246.us-west-1.compute.amazonaws.com</jvm-options>
        <jvm-options>-Ddataverse.rserve.port=6311</jvm-options>
        <jvm-options>-Ddataverse.rserve.user=rserve</jvm-options>
        <jvm-options>-Ddataverse.rserve.password=rserve</jvm-options>
        <jvm-options>-Ddataverse.fqdn=ec2-54-219-54-246.us-west-1.compute.amazonaws.com</jvm-options>
        <jvm-options>-Ddataverse.siteUrl=http://ec2-54-219-54-246.us-west-1.compute.amazonaws.com:8080</jvm-options>
        <jvm-options>-Ddataverse.auth.password-reset-timeout-in-minutes=60</jvm-options>
        <jvm-options>-Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl</jvm-options>
        <jvm-options>-Ddoi.password=apitest</jvm-options>
        <jvm-options>-Ddoi.username=apitest</jvm-options>
        <jvm-options>-Ddoi.baseurlstring=https://ezid.cdlib.org</jvm-options>
        <jvm-options>-Ddataverse.timerServer=true</jvm-options>

I have to check UCLA's EZID setup but otherwise I'm not sure what to look for. 

Right now the test site is at:  <http://ec2-54-219-54-246.us-west-1.compute.amazonaws.com:8080/>

Sorry to keep coming up with these beginner questions.

**Comment by jmjamison** [comment]
I should add that I am able to publish dataverses. It's just the file upload I'm having trouble with.

**Comment by jmjamison** [comment]
Also, not sure if this is significant.  I'm comparing upload steps with the Archive's Harvard hosted dataverse.
Hdataverse:  https://dataverse.harvard.edu/editdatafiles.xhtml?datasetId=58116&mode=UPLOAD
testdataverse:  http://ec2-54-219-54-246.us-west-1.compute.amazonaws.com:8080/dataverse.xhtml?ownerId=2

**Comment by jmjamison** [comment]
And it looks like it may be another beginner type issue - my unfamiliarity with EZID.  Will close this one soon if that's the case.

So, in the future send your absolute beginners to me - I've made all the mistakes in a fairly public way and may be able to answer some questions and save some time.

**Comment by pdurbin** [comment]
@jmjamison ok, please keep us posted. I'm actually a pretty big fan of making mistakes in public. In https://opensource.com/open-organization/17/11/transparency-dataverse-project I wrote, "Community members ask and answer questions in public channels, building a knowledge base accessible by any search engine." 😄

**Comment by jmjamison** [comment]
I believe that I've fixed the EZID issues, using the test account and password 'apitest'. Still can't upload files.  I see the upload animation bar, the files upload, then disappear.  There are files in the /usr/local/dvn/data/temp directory,  There are various empty subdirectories under /usr/local/dvn/data/10.5072.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   415  100   415    0     0  31812      0 --:--:-- --:--:-- --:--:-- 34583
{
  "status": "OK",
  "data": {
    ":Shoulder": "FK2/",
    ":Authority": "10.5072",
    ":SystemEmail": "jamison@library.ucla.edu",
    ":AllowSignUp": "True",
    ":DoiSeparator,": "/",
    ":ShibEnabled": "False",
    ":DoiProvider": "EZID",
    ":BlockedApiPolicy": "localhost-only",
    ":Protocol": "doi",
    ":GoogleAnalyticsCode": "",
    ":BlockedApiEndpoints": "admin,test",
    ":SignUpUrl": "/dataverseuser.xhtml?editMode=CREATE",
    ":FooterCopyright": "UCLA Data Science Center"
  }
}
[ec2-user@ip-172-31-19-240 config]$ 


Sorry to keep bothering you with this,

Jamie

**Comment by pdurbin** [comment]
@jmjamison no worries. I saw this just the other day on one of my servers and what fixed it to me was to stop Glassfish, remove the "/usr/local/glassfish4/glassfish/domains/domain1/generated" directory, and then start Glassfish again. It's weird and I don't understand why but it might be something to try. You can read more about the "generated" directory at at http://guides.dataverse.org/en/4.9.2/admin/troubleshooting.html

**Comment by jmjamison** [comment]
I read the troubleshooting link, removed 'generated' and 'osgi-cache'. Still can't upload.  Next I'm going to try  deleting the rows from the EJB__TIMER__TBL table in the database.

Still picking my way through the log.  One error I found was:
Caused by: java.lang.ClassNotFoundException: edu.harvard.hul.ois.jhove.viewer.ConfigWindow
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1783)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1633)

**Comment by pdurbin** [comment]
@jmjamison huh. Weird. Can you please email support@dataverse.org about this?

**Comment by jmjamison** [comment]
I also tried 'Delete all the rows from the EJB__TIMER__TBL table in the database;'.  Now my add files button is gone.  Will work on that next.

**Comment by jmjamison** [comment]
Hi,

What support told me was:
"From the server log it appears that part of the installation was not completed,
possibly an issue with the Ansible playbook.

The files, jhove.conf and jhove.xsd need to be copied from /dvinstall directory
to the /usr/local/glassfish4/glassfish/domains/domain1/config directory.

Jhove attempts to detect the file type upon upload and if it cannot locate the
jhove files, the upload won't work."

Since the script ended complete I though everything had installed.  I copied over the files listed above and then dataverse  pages wouldn't load at all though Glassfish web console works.  I think I may try reinstalling and then look for the jhove files afterwards.

Jamie


UCLA Library Data Archive
jamison@library.ucla.edu
http://orcid.org/0000-0002-5116-5724
310-825-0716


-----------------------------------------------------------------------------

"An asset is only an asset if you can access it ..."
AMIA (Association of Moving Image Archivists)/Digital Asset Symposium 2008

________________________________________

**Comment by jmjamison** [comment]
I've rerun the ansible install.  I copied over jhove.conf and jhoveConfig.xsd, made glassfish their owener. Still can't upload files. And after creating a dataverse I get the error "Page Not Found - The page you are looking for was not found. " And I keep having to re-log in at each edit - bouncing me back to the the login page.

Back to the jvm options I guess.

**Comment by pameyer** [comment]
I haven't experienced either of those (create dataverse error, or having to re-login after edit); but they might be symptomatic of a problem with the glassfish/postgresql connection.

Could you let us know which linux distribution and postgresql version your system is running on?  

It also looks to me like the various ansible components haven't completed - the URL you listed connects to glassfish; but the apache connection on port 80 or 443 appear to not connect to glassfish.

For testing file upload, it may be helpful to try uploading a file that dataverse won't try to ingest - to sidestep any problems with jhove configs / ingest / etc.

**Comment by jmjamison** [comment]
Red Hat Enterprise Linux Server 7.5 (Maipo) on AWS.   
And, Red Hat Enterprise Linux Server 7.5 (Maipo)

I'll check the AWS network settings.  I may have set that incorrectly.

**Comment by pameyer** [comment]
@jmjamison For the postgresql version, I'd expect something in the 9.X range (`psql --version` should tell you, assuming that the server and client are on the same version, as they'd be if postgres was on the same server as postgresql).

`curl -k https://ec2-54-219-54-246.us-west-1.compute.amazonaws.com` has what appears to be the "welcome to apache" page, suggesting that the AWS network is going to an apache server; but not one that's forwarding requests internally to glassfish.

**Comment by jmjamison** [comment]
Sorry,  psql (PostgreSQL) 9.2.23

**Comment by pameyer** [comment]
Ok - one thing to try would be to copy the `postgresql-42.1.4.jar` file from the installer zip into `$GLASSFISH_ROOT/glassfish/lib` (the same place the ansible role is copying `postgresql-9.1-902.jdbc4.jar`), moving the 9.1 jar out of the way, and restarting glassfish.  I'll defer to folks who are more knowledgeable about postgresql JDBC and server version interactions; but it looks like you may be using a JDBC driver newer than your database server.

It's possible this will not resolve the problem, and it sounds like there's the possibility of multiple problems here - but it might eliminate one potential cause.

**Comment by pdurbin** [comment]
@jmjamison between the ticket and this issue I'm having a little trouble following the status your upload problem. After putting the jhove files into place have the errors in server.log below gone away? And more importantly, does upload work? 😄 

`/editFilesFragment.xhtml @200,65 fileUploadListener="#{EditDatafilesPage.handleFileUpload}": java.lang.NoClassDefFoundError: edu/harvard/hul/ois/jhove/viewer/ConfigWindow`

`javax.el.ELException: /editFilesFragment.xhtml @200,65 fileUploadListener="#{EditDatafilesPage.handleFileUpload}": java.lang.NoClassDefFoundError: edu/harvard/hul/ois/jhove/viewer/ConfigWindow`

**Comment by donsizemore** [comment]
@jmjamison the ansible role needed some updating under the hood since 4.9. try it now?

**Comment by jmjamison** [comment]
I did an upstream pull and merge.  Back to glassfish problems - can't restart server.  

I'm also thinking that some of this may be my inexperience with networking - I may have setup something wrong in AWS networking settings.

**Comment by jmjamison** [comment]
We are going to try that too but I wanted to see what happens with the new version.  I'm trying vagrant right now.  I think it may be running to completion.  I need to figure out what is different.

**Comment by jmjamison** [comment]
Ok,  cleaned out files listed in the documentation on reinstalls AND did a reboot and the install ran to completion.  Just uploaded files.  I think you latest build fixed things.

By the way, can I volunteer/help with documentation? Having made all the beginner errors possible I might be able to see what may need highlighting.

**Comment by pdurbin** [comment]
@jmjamison yes! Please see our "Help Wanted: Documentation" label at https://github.com/IQSS/dataverse/labels/Help%20Wanted%3A%20Documentation and if there's something that should be documented, please create an issue at https://github.com/IQSS/dataverse/issues . Thanks! I'm glad things are working. Credit to @donsizemore for making the updates and fixes!
