### ISSUE TITLE
Support EC2 guides

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse-ansible#209]
Another low priority feature request. Had a lil back and forth in the Slacks trying to get changes to the guides up on a server to put some eyeballs and cursors on. It would be super neat if the super awesome EC2 spin up scripts built the guides, so that I could go to a url like `http://ec2-000-00-000-000.compute-1.amazonaws.com/en/{BRANCH-NAME}/user/` and see my changes.

**Comment by donsizemore** [comment]
Using the dataverse-ansible role for this would really be overkill. Instead I've offered to cobble together an ec2-create equivalent for the guides, possibly to live in https://github.com/IQSS/dataverse/tree/develop/doc/sphinx-guides

**Comment by donsizemore** [comment]
@pdurbin says this isn't overkill. In this morning's use case @mheppler wanted the guides without the Dataverse instance, but it could be helpful to build updated guides along with a given branch.
