### ISSUE TITLE
enable spinning up of arbitrary branches

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#22]
I'm aware that there's a "version" variable that's incremented in 236dabc for example (4.9 to 4.9.2) but the Dataverse dev team and IQSS is interested in trying to allow an arbitrary branch (usually unmerged) to be spun up, as explained at https://github.com/IQSS/dataverse/issues/4990

**Comment by donsizemore** [comment]
i propose an optional branch variable that would do a `git clone` and `mvn package` instead of deploying the warfile included in dvinstall.zip. shouldn't really require that much modification.

**Comment by donsizemore** [comment]
sticking a fork in this one. @pdurbin let me know if it should be re-opened.
