### ISSUE TITLE
Running ansible inside EC2 instance?

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse-ansible#24]
As part of [this issue](https://github.com/IQSS/dataverse/issues/4990) in the Dataverse repo, we are looking into ways to spin up branches for better testing and design use. The goal is to script the creation of AWS EC2 instances that we can then run Dataverse inside. 

I have a script working that creates the Centos 7 AWS EC2 instance and drops in the name of a branch to be deployed (into a text file). My understanding from talking to @pdurbin (who is away at a conference) is that I should be able to leverage this Ansible repo to deploy the resources needed by Dataverse. I am a bit confused reading through this repo on how to move forward, as a lot of this works seems to be for using vagrant alongside ansible. I'm also confused because the usage line in the `README.md` points to a dataverse.pb file that seems to have been pulled from the repo during refactor.

I am admittedly a complete ansible noob but if any guidance can be provided it would be a lot of help! Thanks!

**Comment by donsizemore** [comment]
hey hey, this repo can use vagrant but doesn’t require it. the .pb may be part of trevor’s work, but i’m happy to walk you through the bit and pieces?

we can zoom or skype or gchat or send smoke signals over the next two days if you like? UNC is closed for the Flopocalypse but i’ll be on from home.

D

**Comment by matthew-a-dunlap** [comment]
@donsizemore Sounds great! I'm pretty free tomorrow, we can chat about it. I get in on the later side, maybe let's shoot for early afternoon?

**Comment by donsizemore** [comment]
tentatively sticking a fork in this one.
