### ISSUE TITLE
lots of errors in logs about not being able to send email to smtp.yourinstitution.edu when doing basic tasks in app

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#28]
"lots of errors in logs about not being able to send email to smtp.yourinstitution.edu when doing basic tasks in app" https://github.com/IQSS/dataverse/issues/4990#issuecomment-425267670

The context above is the new "spin up arbitrary branches on AWS" script we wrote in that issue.

**Comment by donsizemore** [comment]
dataverse.smtp should be set to a real smtp server. if it's throwing errors on screen i can set it to mailinator by default, but... this is expected behavior.

**Comment by pdurbin** [comment]
@donsizemore sure. Makes sense. Do you (or anyone reading this) have any suggestions on an easy way to configure Dataverse to actually send email when we spin it up on AWS with our script? I know that in https://github.com/IQSS/dataverse/pull/5039 we recently documented how to configure Dataverse to use Amazon Simple Email Service (SES).

I guess my point is that for the purposes of our "spin up" script, I *think* the change needs to happen on the Ansible side.

Of course, at https://github.com/IQSS/dataverse/issues/4990#issuecomment-422464237 we talked about someday supporting the notion of a settings file to pass prior to deployment. So maybe we want support for a settings file? I'm not sure what I want but I'm duly reporting the desire to be able to send email. 😄

**Comment by donsizemore** [comment]
@pdurbin I mean, if you really want I can put in an optional localhost/smtp task so the host itself can send e-mail. a (very brief) google search didn't yield an amazon mail relay, but in general i'd expect this to be set per organization.

we can default to localhost and stand up our own smtp, if dataverse.smtp isn't defined?

**Comment by pdurbin** [comment]
That's one thought I had... good old localhost! 😄

**Comment by donsizemore** [comment]
I changed the setting to localhost at some point but didn't close this issue. Closing.

**Comment by pdurbin** [comment]
@donsizemore thanks!
