### ISSUE TITLE
properly support configurable dataverseAdmin password

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-ansible#31]
per https://github.com/IQSS/dataverse/pull/5201/commits/791d1fa6a2fbdf116fb6a23b85d430f50b4fbd76

**Comment by donsizemore** [comment]
settings are in place; waiting for 4.9.5 when pete's setup-all.sh changes are incorporated.

**Comment by pdurbin** [comment]
@donsizemore that's totally fine but in theory we could use the latest code in "develop" or any arbitrary branch, right? For the uninitiated, that's what http://guides.dataverse.org/en/4.9.4/developers/deployment.html#deploying-dataverse-to-amazon-web-services-aws is about.

**Comment by donsizemore** [comment]
@pdurbin i can break one or the other, so in my mind release won out. 4.9.5 is just around the corner anyway.

**Comment by pdurbin** [comment]
Oh! I hadn't heard. Thanks.

**Comment by pdurbin** [comment]
@donsizemore I'm closing this because with the group vars support it's easy to set the dataverseAdmin password. I even mentioned this specifically at https://github.com/IQSS/dataverse/commit/3bdf6c9c5361ea0151816c5379c243fd8b8189fa
