### ISSUE TITLE
include Make Data Count processor

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-ansible#33]
per [Phil's script](https://github.com/IQSS/dataverse/blob/0bfd93654eb153976fb548b7cc4a4aa3df1f18e4/scripts/vagrant/setup-counter-processor.sh)

**Comment by pdurbin** [comment]
@donsizemore thanks for creating this issue! I also created https://github.com/IQSS/dataverse/issues/5440 so we can track this at https://waffle.io/IQSS/dataverse and discuss it at standup, etc.

**Comment by pdurbin** [comment]
@donsizemore I'm going to forget what I'm seeing so I hope you don't mind if I scatter comments in here.

FileNotFoundError: [Errno 2] No such file or directory: 'maxmind_geoip/GeoLite2-Country.mmdb

workaround:

cp maxmind_geoip/GeoLite2-Country_20190108/GeoLite2-Country.mmdb maxmind_geoip/GeoLite2-Country.mmdb

**Comment by pdurbin** [comment]
@donsizemore do you want me to take a swing at fixing the GeoLite2-Country.mmdb thing? Please check out this new page I added yesterday: https://github.com/IQSS/dataverse/blob/e55574c0644eebcfa3a40304fbb42a03f601df75/doc/sphinx-guides/source/developers/make-data-count.rst#dev-environment-setup-for-make-data-count
