### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gitLee47** [IQSS/dataverse-ansible#4]
I am getting the following error when I'm trying to install from windows using vagrant.
Does anyone have a suggestion?

==> default: TASK: [dataverse | start glassfish with asadmin so subsequent Ansible-initiated restarts succeed on RedHat/CentOS] ***
==> default: <127.0.0.1> REMOTE_MODULE command nohup /usr/local/glassfish4/bin/asadmin start-domain #USE_SHELL
==> default: c
==> default: hanged: [dataverse] => {"changed": true, "cmd": "nohup /usr/local/glassfish4/bin/asadmin start-domain", "delta": "0:00:16.131758", "end": "2016-11-11 20:20:36.225497", "rc": 0, "start": "2016-11-11 20:20:20.093739", "stderr": "nohup: ignoring input", "stdout": "Waiting for domain1 to start .............\nSuccessfully started the domain : domain1\ndomain  Location: /usr/local/glassfish4/glassfish/domains/domain1\nLog File: /usr/local/glassfish4/glassfish/domains/domain1/logs/server.log\nAdmin Port: 4848\nCommand start-domain executed successfully.", "warnings": []}
==> default:
==> default: TASK: [dataverse | start glassfish on Debian/Ubuntu] **************************
==> default: skipping: [dataverse]
==> default:
==> default: TASK: [dataverse | download solr. unarchive urls supported in 2.0.] ***********
==> default: <127.0.0.1> REMOTE_MODULE get_url url=https://archive.apache.org/dist/lucene/solr/4.6.0/solr-4.6.0.tgz dest=/tmp mode=0644
==> default: failed: [dataverse] => {"failed": true}
==> default: msg: failed to create temporary content file: The read operation timed out
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: PLAY RECAP ********************************************************************
==> default:            to retry, use: --limit @/root/dataverse.yaml.retry
==> default:
==> default: dataverse                  : ok=27   changed=26   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by donsizemore** [comment]
Hello, I'm unable to reproduce this, though I'm on Linux and a University network.

Can you reproduce this reliably? Could it have been a transient error contacting archive.apache.org?

**Comment by pdurbin** [comment]
My money is on transient error. Not long after this issue was created I clicked https://archive.apache.org/dist/lucene/solr/4.6.0/solr-4.6.0.tgz and accidentally downloaded Solr to my phone. What an age we live in.

**Comment by gitLee47** [comment]
I guess it is due to a timeout factor. I destroyed the vagrant box then recreated it..next time it failed at another point. I then switched off my firewall, anti virus and all network intensive applications, took my laptop sat next to the wifi router and ran vagrant up. It ran to completion. However, I was not able to access dataverse. The url was only fetching me glassfish. I then created a Centos 7 VM and deployed dataverse on it. I have that running now.

**Comment by pdurbin** [comment]
@gitLee47 yikes! What a terrible user experience! Probably Dataverse silently failed to deploy or something. Thanks for sticking with it! If you have any more problems, please reach out via one of the channels at http://dataverse.org/contact

**Comment by gitLee47** [comment]
Will do. Thanks. I will however try to setup  dataverse-ansible later, just for curiosity's sake. It might also have been due to some port forwarding issue. Will update this post later if I'm able to find anything. Closing this for now.
