### ISSUE TITLE
Install Script - Default credentials are different

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse-ansible#44]
The default credentials are different depending on which install script you use. As a first time deployer of the ansible version on AWS, I had to ask around to those with more experience to learn the default `dataverseAdmin` password is different.

**Comment by pdurbin** [comment]
For what it's worth, on the phoenix server I use "admin1" as the default password:

https://github.com/IQSS/dataverse/blob/v4.11/scripts/deploy/phoenix.dataverse.org/post#L3

**Comment by pdurbin** [comment]
dataverse-ansible uses "notPr0d" for both the dataverseAdmin password and the Glassfish password:

<img width="380" alt="screen shot 2019-02-26 at 6 46 56 pm" src="https://user-images.githubusercontent.com/21006/53454963-fcf28100-39f6-11e9-942f-619d881c1599.png">

**Comment by mheppler** [comment]
https://github.com/IQSS/dataverse/issues/4178
