### ISSUE TITLE
Playbook assumes that sudo is present

### ISSUE THREAD

**Issue by atc0005** [IQSS/dataverse-ansible#45]
We're going through the process of using the playbooks for the first time within LXD CentOS 7 containers and encountered an error regarding a missing `sudo` command:

```
TASK [dataverse : start glassfish with asadmin so subsequent Ansible-initiated restarts succeed on RedHat/CentOS] *******************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: sudo: command not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}
	to retry, use: --limit @/root/dataverse.retry

PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=37   changed=32   unreachable=0    failed=1   

```

Installing the `sudo` package resolves the issue. Please let me know if you'd like a PR for this.

**Comment by pdurbin** [comment]
@atc0005 yes, please ahead. I can't imagine that @donsizemore would object to a pull request. Thanks!

**Comment by donsizemore** [comment]
@atc0005 I was going to just fix it, but I have yet to refuse a pull request =) 

Admittedly I've never used LXD — just need to add sudo alongside the other initial package installs?

**Comment by atc0005** [comment]
> @atc0005 yes, please go ahead. I can't imagine that @donsizemore would object to a pull request. Thanks!

PR submitted.

> @atc0005 I was going to just fix it, but I have yet to refuse a pull request =)

Admittedly it was a small change. :)

> Admittedly I've never used LXD — just need to add sudo alongside the other initial package installs?

I think so. I'm running into an error myself when using the playbook, but a friend of mine isn't running into the same issue after installing the sudo package.

I'm going to work with him today to try and work out what step I'm missing with my test deployment.

**Comment by pdurbin** [comment]
@atc0005 I approved the PR. Looks good. In an hour or so I'll be in http://chat.dataverse.org if you want to chat in real time about your trouble. You'll find @donsizemore in there a lot too. You and your friend are more than welcome! Thanks for the pull request!

**Comment by atc0005** [comment]
Thanks!

Thanks also for the offer of discussing the issues over chat. After some further local testing, I *believe* we've isolated the issue I was encountering. I'll open a separate issue for that to keep things (hopefully) clearer.

Please feel free to close this issue out when ready.
