### ISSUE TITLE
the Perl script at roles/dataverse/templates/install.de.j2 is unused and should be deleted

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#5]
I'm looking at the Perl script at https://github.com/IQSS/dataverse-ansible/blob/master/roles/dataverse/templates/install.de.j2 and wondering if it's used anywhere. I can only assume it's there for a reason but I can't tell where it gets called.

If that install.de.j2 file is used, I'd imagine that one would always be looking upstream to see if the Perl script changed when Dataverse releases a new version, https://github.com/IQSS/dataverse/blob/v4.6.2/scripts/installer/install for example.

I'm asking because in https://github.com/IQSS/dataverse/issues/3937 (comments welcome!) we're talking about switching from Perl to something else. I'm wondering if the Dataverse developers should adopt Ansible. I haven't played with this repo much but I use parts of https://github.com/pdurbin/dataverse-osx-playbook for my dev environment (see also "pick your poison" at http://bl.ocks.org/pdurbin/raw/7847a0642f8bd6601a07c3619b4a35f6/#2 ).

**Comment by pdurbin** [comment]
I just got a preliminary answer at https://irclog.perlgeek.de/crimsonfu/2017-06-24 that the `install.de.j2` file is not used.

**Comment by donsizemore** [comment]
agreed: |dls@irss-dls:~/dataverse-ansible| grep -r install.de.j2 .
Binary file ./.git/index matches

sorry for the delay; we had a going-away party for our director yesterday. Ansible is great for installing Dataverse, but the unique/specific nature of each Dataverse upgrade may challenge Ansible's goal of idempotence.

**Comment by donsizemore** [comment]
removed and tested in vagrant against 4.7. closing.

**Comment by pdurbin** [comment]
@donsizemore thanks! For a bit of discussion on this: http://irclog.iq.harvard.edu/dataverse/2017-06-26#i_53649
