### ISSUE TITLE
Does this role support running Dataverse in a suburi?

### ISSUE THREAD

**Issue by atc0005** [IQSS/dataverse-ansible#50]
For example, we're attempting to run Dataverse in a container and have Apache on a different host reverse-proxy connections to port 8080 exposed on the container host. From what I can recall, the application receiving connections has to be told about the sub-uri in order to properly generate URLs that reference it, otherwise sub-URI references refer to the base '/' path instead.

I didn't spot this support in the role `defaults/main.yml` file, but wanted to double-check and make sure I wasn't overlooking anything.

Thanks.

**Comment by pdurbin** [comment]
@atc0005 I might need a little help understanding.

Usually, people run Dataverse at URLs like https://myarchive.example.com and dataset pages appear at URLs like https://myarchive.example.com/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCLKP

Are you asking if it's possible to run Dataverse at a URL like https://example.com/myarchive with dataset landing pages at https://example.com/myarchive/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCLKP?

**Comment by atc0005** [comment]
@pdurbin Exactly. Because we're going with a test instance for right now, it would be ideal if we could run database at a url like https://example.com/dataverse/ for testing purposes. This would allow us to use the existing web server certificate, existing firewall rules and access requirements, etc.

Thanks for the response.

**Comment by pdurbin** [comment]
@atc0005 hmm, I'm not sure if this is possible. You might want to ask at https://groups.google.com/forum/#!forum/dataverse-community if anyone has tried.

**Comment by atc0005** [comment]
> @atc0005 hmm, I'm not sure if this is possible. You might want to ask at https://groups.google.com/forum/#!forum/dataverse-community if anyone has tried.

@pdurbin Thanks for the feedback. If it's not (easily) possible in dataverse itself then it's probably not within the scope of the role to apply the changes. If I learn differently I'll try to come back and reopen this and supply useful information at that time.

CC: @auadamw
