### ISSUE TITLE
As someone spinning up Dataverse on EC2, I want valid SSL certs

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#53]
We should add Let's Encrypt or whatever.

**Comment by donsizemore** [comment]
@pdurbin user-supplied certs should be working in my 53 branch; got part-way through Certbot setup this afternoon but http verification is throwing errors. Looking into other verification methods, will pick it back up Monday.

**Comment by pdurbin** [comment]
@donsizemore wow! Great! 🎉

**Comment by donsizemore** [comment]
certs are supported; certbot is problematic in vagrant testing because certbot only wants port 80 but vagrant can only grab ports <1024 when launched as root. per http://irclog.iq.harvard.edu/dataverse/2019-05-03#i_92359 i'm tabling certbot support for a later date (TLS-ALPN-01 on the Vulcan calendar)

**Comment by pdurbin** [comment]
@donsizemore I tried putting my PEM files in mail.yml and it worked!! I was able to put my dev2 cert on a new ec2 instance without having to ssh into the box or hack on my local copy of the ec2 create script. This is great. Next step is to create a wildcard cert, maybe? Also, the syntax is non-intuitive to so we **could** change main.yml to something like this:

```
apache:
  ssl:
    enabled: false
    cert: 
    interm: 
    key: 
    pem:
      cert: |
        -----BEGIN CERTIFICATE-----
        Put your main cert here.
        -----END CERTIFICATE-----
      interm: | 
        -----BEGIN CERTIFICATE-----
        Put your intermediate cert here.
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        Put your private key here.
        -----END RSA PRIVATE KEY-----
```

https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#set-up-manual-https is where you found this syntax. Thanks for linking me to it.

I'm also wondering if once I create a wildcard cert we could just hard code the "cert" and "interm" fields and maybe have the private key be pulled from somewhere safe? Maybe `~/.dataverse/ec2-private.key` or something? I'm not trying to add scope to this issue. What we've got now is fantastic! I'm just thinking out loud. 😄

**Comment by donsizemore** [comment]
@pdurbin yes on documentation, but if we populate the vars defaults.yml with examples, ansible will fire them off.

"PEMs vs. files" is currently an either/or choice, but I could put the logic in to support say a private key as a file but certs as PEMs, if you think it's worth it?

**Comment by pdurbin** [comment]
@donsizemore probably not. Let's talk it out in chat sometime and figure out the definition of done for this issue. 😄 What you've done so far is fantastic. Ansible won't fire the PEMs if enabled is set to false, right? Or will it?!? 🤔 😕 🤔

**Comment by donsizemore** [comment]
@pdurbin it won't fire the PEMs if ssl.enabled == false, but i could stick in a pems.enabled == false to allow the inclusion of your suggested examples?

**Comment by pdurbin** [comment]
@donsizemore I'm closing this. We discussed it a couple weeks ago and I'm in a good place these days. I said I'd share with you my "spin up dev2" scripts, which I've been using for weeks.

The idea is that for https://dev2.dataverse.org I maintain the following:

- dev.yaml: all my favorite group vars features
- dev2.certs: my secret secret private key

Then I run a couple script to shove the secret stuff into the group vars file.

```
$ cat spin-up-dev2.sh 
#!/bin/sh
./prepare-dev2.sh > dev2.yaml
./ec2-create-instance.sh -g dev2.yaml
```

```
$ cat prepare-dev2.sh 
#!/bin/sh
# Redirect the output to dev2.yaml
# https://superuser.com/questions/440013/how-to-replace-part-of-a-text-file-between-markers-with-another-text-file/440057#440057
CERTS_FILE=dev2.certs
lead='^apache:$'
tail='^      interm: $'
# The terminating ``}'' must be preceded by a newline or optional white space.
sed -e "/$lead/,/$tail/{ /$lead/{p; r $CERTS_FILE
}; /$tail/p; d; }" dev.yaml | sed "/$tail/d"
```

```
$ cat dev.yaml 
---
# dataverse/defaults/main.yml

apache:
  ssl:
    enabled: false
    cert: 
    interm: 
    key: 
    pem:
      cert: 
      key: 
      interm: 

letsencrypt:
  enabled: false
  certbot:
    autorenew: true
    email:
    user: certbot

dataverse:
  adminpass: admin1
[snip]
```

```
$ cat dev2.certs 
  ssl:
    enabled: true
    cert: 
    interm: 
    key: 
    pem:
      cert: |
        -----BEGIN CERTIFICATE-----
        [REDACTED]
        -----END CERTIFICATE-----
      interm: | 
        -----BEGIN CERTIFICATE-----
        [REDACTED]
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        [REDACTED]
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        [REDACTED]
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        [REDACTED]
        -----END RSA PRIVATE KEY-----
```
