### ISSUE TITLE
As someone kicking the tires on Dataverse, I'd like to play around with the Whole Tale external tool

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#59]
The latest docs are at https://wholetale.readthedocs.io/en/stable/users_guide/integration.html#dataverse-external-tools

Via http://guides.dataverse.org/en/4.12/installation/external-tools.html

**Comment by pdurbin** [comment]
@donsizemore works great! https://github.com/IQSS/dataverse/issues/5455#issuecomment-480325771 Thanks!

**Comment by pdurbin** [comment]
@donsizemore I reconfigured another ec2 instance for just http but somehow whole tale wants https, maybe? Please check out these screenshots:

![Screen Shot 2019-04-05 at 12 15 55 PM](https://user-images.githubusercontent.com/21006/55641858-ecbf8580-579c-11e9-82f7-9067709b867f.png)
![Screen Shot 2019-04-05 at 12 16 03 PM](https://user-images.githubusercontent.com/21006/55641859-ecbf8580-579c-11e9-9c62-0cd27c5198ce.png)
![Screen Shot 2019-04-05 at 12 16 08 PM](https://user-images.githubusercontent.com/21006/55641860-ecbf8580-579c-11e9-88ff-5933e6252e3f.png)
![Screen Shot 2019-04-05 at 12 16 18 PM](https://user-images.githubusercontent.com/21006/55641861-ecbf8580-579c-11e9-89a9-6755a316a1a6.png)
![Screen Shot 2019-04-05 at 12 16 29 PM](https://user-images.githubusercontent.com/21006/55641862-ecbf8580-579c-11e9-8467-f468d42c9205.png)
![Screen Shot 2019-04-05 at 12 16 48 PM](https://user-images.githubusercontent.com/21006/55641863-ecbf8580-579c-11e9-81e2-17a4d337ba7c.png)
![Screen Shot 2019-04-05 at 12 17 13 PM](https://user-images.githubusercontent.com/21006/55641864-ecbf8580-579c-11e9-854d-f332ca5b879e.png)

**Comment by Xarthisius** [comment]
@pdurbin I'm afraid it won't work out of the box, since WT will not recognize that the dataset comes from Dataverse, as we whitelist the supported DV instances.

**Comment by pdurbin** [comment]
@Xarthisius uh oh. That's a blocker for me wanting to demo the integration between Dataverse and Whole Tale in June at our community meeting ( https://dataverse.org/events ). You're saying we need a brave volunteer to enable the Whole Tale button in their production installation of Dataverse? Or can we whitelist a couple non-production installations?

**Comment by Xarthisius** [comment]
We can whitelist whatever you need. I was merely stating it requires human intervention. :)

**Comment by pdurbin** [comment]
@Xarthisius great! As a start, can you please whitelist the following?

- https://demo.dataverse.org
- http://phoenix.dataverse.org
- http://beta.dataverse.org
- https://dev1.dataverse.org
- https://dev2.dataverse.org

Is HTTPS required? Judging from the screenshot above, Whole Tale was trying to download file "29" over HTTPS even though I clicked "Explore" from a Dataverse installation on HTTP (no S).

**Comment by Xarthisius** [comment]
Unless it's hardcoded somewhere by mistake it should use the same scheme as the original url. I white-listed those host on our .stage.wholetale.org deployment (you'll need to update external tools json). It should be fairly stable.
