### ISSUE TITLE
Glasshfish download with vagrant failes

### ISSUE THREAD

**Issue by mdehollander** [IQSS/dataverse-ansible#6]
I am running the ansible playbook with vagrant and get this error:

`
==> default: TASK: [dataverse | download and unzip glassfish4] ***************************** 
==> default: failed: [dataverse] => {"failed": true}
==> default: msg: Source 'http://dlc-cdn.sun.com/glassfish/4.1/release/glassfish-4.1.zip' does not exist
==> default: 
==> default: FATAL: all hosts have already failed -- aborting
==> default: 
==> default: PLAY RECAP ******************************************************************** 
==> default:            to retry, use: --limit @/root/dataverse.pb.retry
==> default: 
==> default: dataverse                  : ok=22   changed=21   unreachable=0    failed=1   
`

It says it can not find the glassfish zip file, but when I open the link in a browser I get a download presented. Any ideas how to fix this?

**Comment by mdehollander** [comment]
@donsizemore, can it be that the quotes around the link at https://github.com/IQSS/dataverse-ansible/blob/master/roles/dataverse/tasks/dataverse-glassfish.yaml are causing this issue?

**Comment by donsizemore** [comment]
Weird - all those same unarchive calls were working as of the 4.7 release. I wound up switching them to get_url - try it now?

**Comment by mdehollander** [comment]
Thanks for the quick fix. It gets a step further now, but I ran into an issue install shibboleth: https://github.com/IQSS/dataverse-ansible/issues/7
