### ISSUE TITLE
dataverse.siteUrl JVM option required for many features

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#61]
As discussed in https://github.com/IQSS/dataverse/issues/4517 the JVM option `dataverse.siteUrl` is very important for a properly functioning installation of Dataverse.

Yesterday I spun up an EC2 instance and forgot to set it before asking @jggautier to try export. He got to http://ec2-100-27-31-230.compute-1.amazonaws.com:8080/dataset.xhtml?persistentId=doi:10.5072/FK2/G251YB ok but when he clicked export he got https://dataverse.yourinstitution.edu/api/datasets/export?exporter=oai_datacite&persistentId=doi%3A10.5072/FK2/G251YB which won't work, of course.

The challenge (the fun!) of this is that on EC2 we tell people to start on URLs like http://ec2-100-27-31-230.compute-1.amazonaws.com:8080 and we can't know in advance what the hostname will be. So I can't put `http://ec2-100-27-31-230.compute-1.amazonaws.com:8080` into my main.yml file. Instead, we have to update domain.xml afterwards. I've been doing this manually (and coached @mheppler through it, who took notes) but it would be great to automate this in some way.

**Comment by donsizemore** [comment]
we can create a group_var for this to allow it to be set to a known/desired siteurl beforehand, but let it otherwise default to the system hostname. i'll add this before i continue on the proxy stuff.

**Comment by pdurbin** [comment]
@donsizemore sounds great but heads up that the system hostname is different than the hostname used in the URL:

- `hostname`: ip-172-31-80-75.ec2.internal
- hostname in public URL: ec2-100-27-31-230.compute-1.amazonaws.com

Something like this should work:

`curl -s ipv4bot.whatismyipaddress.com | xargs host | cut -d' ' -f5`

**Comment by donsizemore** [comment]
@pdurbin apparently one may do this within EC2 by calling http://169.254.169.254/latest/meta-data/public-hostname

**Comment by matthew-a-dunlap** [comment]
@donsizemore you are probably already aware of this as you are actively working on it, but as of an hour ago the set siteUrl  step blows up deploying an ec2 instance. the `:`'s need to be escaped for the jvm options

**Comment by matthew-a-dunlap** [comment]
```
TASK [dataverse : set siteurl] *************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/glassfish4/bin/asadmin create-jvm-options \"-Ddataverse.siteUrl={u'status': 200, u'content_length': u'42', u'cookies': {}, 'failed': False, u'url': u'http://169.254.169.254/latest/meta-data/public-hostname', u'changed': False, u'server': u'EC2ws', u'date': u'Fri, 12 Apr 2019 16:30:15 GMT', u'connection': u'close', u'last_modified': u'Fri, 12 Apr 2019 16:23:59 GMT', u'etag': u'\"807346093\"', u'content_type': u'text/plain', u'msg': u'OK (42 bytes)', u'redirected': False, u'accept_ranges': u'bytes', u'cookies_string': u''}\"", "delta": "0:00:00.466113", "end": "2019-04-12 16:30:16.220582", "msg": "non-zero return code", "rc": 1, "start": "2019-04-12 16:30:15.754469", "stderr": "remote failure: JVM option  200, ucontent_length is invalid because it does not start with a '-'", "stderr_lines": ["remote failure: JVM option  200, ucontent_length is invalid because it does not start with a '-'"], "stdout": "Command create-jvm-options failed.", "stdout_lines": ["Command create-jvm-options failed."]}
	to retry, use: --limit @/home/centos/dataverse/dataverse.retry
```

**Comment by donsizemore** [comment]
@matthew-a-dunlap yeah, things that are quite simple locally become much messier in EC2. my apologies for being lazy and not using a branch.

**Comment by matthew-a-dunlap** [comment]
Loaded up great now, thanks Don!

**Comment by donsizemore** [comment]
@pdurbin tested this again today, works as expected. closing.
