### ISSUE TITLE
allow custom SSH publickeys

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-ansible#62]
for benefit of EC2

**Comment by pdurbin** [comment]
Yes! Ideally we'd be able to specify multiple, like this:

- https://github.com/pdurbin.keys
- https://github.com/larsks.keys

**Comment by donsizemore** [comment]
in theory, i can allow a list of both URLs or local files in the defaults yaml. at least, that's plan "A"

**Comment by donsizemore** [comment]
Working as advertised for me in local testing, and for @pdurbin at http://irclog.iq.harvard.edu/dataverse/2019-04-26#i_91941
