### ISSUE TITLE
support API test suite

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-ansible#65]
is it really as simple as

`mvn test -Dtest=DataversesIT,DatasetsIT,SwordIT,AdminIT,BuiltinUsersIT,UsersIT,UtilIT,ConfirmEmailIT,FileMetadataIT,FilesIT,SearchIT,InReviewWorkflowIT,HarvestingServerIT,MoveIT,MakeDataCountApiIT -Ddataverse.test.baseurl=`

**Comment by pdurbin** [comment]
@donsizemore yes, but the list of test changes over time so it would be better to call the run-test-suite.sh script mentioned at http://guides.dataverse.org/en/4.13/developers/testing.html

As of 4.13 it can be found at https://github.com/IQSS/dataverse/blob/v4.13/conf/docker-aio/run-test-suite.sh

I am certainly open to a pull request to put that script in a better place as well as not being hard coded to port 8084 by default. 8080 makes more sense to me day to day since I often run it on localhost.

**Comment by pdurbin** [comment]
@donsizemore thanks for pull request #66! Maybe I should be asking this over at https://github.com/IQSS/dataverse-jenkins but will https://jenkins.dataverse.org be able to produce a "Test Result" page based on the API test suite like https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/edu.harvard.iq$dataverse/387/testReport/edu.harvard.iq.dataverse.api/ ? Here's a screenshot:

![Screen Shot 2019-05-07 at 11 40 43 AM](https://user-images.githubusercontent.com/21006/57313141-f77f7a00-70bc-11e9-910c-8b48597a5854.png)

**Comment by donsizemore** [comment]
test results page from jenkins.dataverse.org:
![Screen Shot 2019-08-19 at 10 08 22](https://user-images.githubusercontent.com/12831666/63272019-4ff01700-c269-11e9-9930-403f9d62ab3b.png)

**Comment by pdurbin** [comment]
This issue reflects pretty well what @donsizemore and I are working on at the moment on the road toward #67 so I dragged it to https://github.com/orgs/IQSS/projects/2#column-5298409 . Making good progress.

**Comment by pdurbin** [comment]
Great progress. The API test suite almost passed with this command:

./ec2-create-instance.sh -g ec2config.yaml -r https://github.com/IQSS/dataverse.git -b develop -a 65_api_test_suite

I'm on the following commits:

- https://github.com/IQSS/dataverse/commit/6bebe7f
- https://github.com/IQSS/dataverse-ansible/commit/7071697

The output is a bit hard to read but I'll paste it here anyway in plain text and as a screenshot.

",", "                \"published_at\": \"2019-09-25T15:02:39Z\",", "                \"citationHtml\": \"Finch, Fiona, 2019, \\\"Darwin's Finches\\\", <a href=\\\"https://doi.org/10.5072/FK2/BAACS1\\\" target=\\\"_blank\\\">https://doi.org/10.5072/FK2/BAACS1</a>, Root, V1\",", "                \"identifier_of_dataverse\": \"dvf9c92928\",", "                \"name_of_dataverse\": \"dvf9c92928\",", "                \"citation\": \"Finch, Fiona, 2019, \\\"Darwin's Finches\\\", https://doi.org/10.5072/FK2/BAACS1, Root, V1\",", "                \"authors\": [", "                    \"Finch, Fiona\"", "                ]", "            }", "        ],", "        \"count_in_response\": 1", "    }", "}", "[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.446 s <<< FAILURE! - in SearchIT", "[ERROR] testNestedSubtree  Time elapsed: 1.644 s  <<< FAILURE!", "java.lang.AssertionError: ", "JSON path data.total_count doesn't match.", "Expected: <2>", "  Actual: 1", "", "\tat edu.harvard.iq.dataverse.api.SearchIT.testNestedSubtree(SearchIT.java:749)", "", "[INFO] ", "[INFO] Results:", "[INFO] ", "[ERROR] Failures: ", "[ERROR]   SearchIT.testNestedSubtree:749 JSON path data.total_count doesn't match.", "Expected: <2>", "  Actual: 1", "", "[ERROR] Errors: ", "[ERROR]   ExternalToolsIT.testFileLevelTool1:130 » IllegalArgument Cannot get property '...", "[INFO] ", "[ERROR] Tests run: 103, Failures: 1, Errors: 1, Skipped: 4", "[INFO] ", "[INFO] ------------------------------------------------------------------------", "[INFO] BUILD FAILURE", "[INFO] ------------------------------------------------------------------------", "[INFO] Total time: 3:39.092s", "[INFO] Finished at: Wed Sep 25 15:02:40 UTC 2019", "[INFO] Final Memory: 60M/484M", "[INFO] ------------------------------------------------------------------------", "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project dataverse: There are test failures.", "[ERROR] ", "[ERROR] Please refer to /tmp/dataverse/target/surefire-reports for the individual test results.", "[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.", "[ERROR] -> [Help 1]", "[ERROR] ", "[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.", "[ERROR] Re-run Maven using the -X switch to enable full debug logging.", "[ERROR] ", "[ERROR] For more information about the errors and possible solutions, please read the following articles:", "[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException"]}

<img width="1266" alt="Screen Shot 2019-09-25 at 11 04 51 AM" src="https://user-images.githubusercontent.com/21006/65613673-671ad680-df84-11e9-8089-5778a23b5324.png">

**Comment by donsizemore** [comment]
We have everything passing except SearchIT. Okay to close this issue?

**Comment by pdurbin** [comment]
@donsizemore I took you off it. Thanks for all your help! I'm going to keep hacking on it until I get all the tests passing, including SearchIT. So let's leave it open for now. Thanks!

**Comment by pdurbin** [comment]
@donsizemore I changed my mind. I'm closing this because you HAVE successfully implemented the running of the API test suite (THANKS!) To look into that specific SearchIT failure, I opened https://github.com/IQSS/dataverse/issues/6270
