### ISSUE TITLE
Support for Data Curation Tool

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#88]
I know I'm jumping the gun and that the Data Curation Tool doesn't have installations instructions yet ( https://github.com/scholarsportal/Dataverse-Data-Curation-Tool/issues/4 ) but I'd love to be able to demo this on a newly spun up EC2 instance some day.

**Comment by pdurbin** [comment]
There are now installation instructions at https://github.com/scholarsportal/Dataverse-Data-Curation-Tool#installation

By the way, I was chatting with @kcondon the other day and he tried the tool. I haven't tried it yet myself but I'm looking forward to it. 😄

**Comment by donsizemore** [comment]
going to include the "demo" version running off GitHub for now. can also compile into Dataverse warfile or install standalone if desired.

**Comment by pdurbin** [comment]
@donsizemore fantastic! Yeah now that there are nice docs at https://spotdocs.scholarsportal.info/display/DAT/2019/09/26/Introducing+the+Data+Curation+Tool (via https://twitter.com/scholarsportal/status/1177231708518780930 ) it would be great to tweet back and say "just spin it up with dataverse-ansible!" :smile: Thanks for working on this!! :tada: :tada: :tada:

**Comment by donsizemore** [comment]
`ERROR\",\"message\":\"Unknown reserved word: {localeCode}`

**Comment by pdurbin** [comment]
@donsizemore perfect. "localeCode" is coming in https://github.com/IQSS/dataverse/issues/6215

**Comment by pdurbin** [comment]
I just merged #88! Thanks, @donsizemore !! Closing!

**Comment by pdurbin** [comment]
@donsizemore thanks again for working on this. I now have the Data Curation Tool on my https://dev2.dataverse.org and over at https://github.com/IQSS/dataverse.harvard.edu/issues/32 I'm suggesting we add it to Harvard Dataverse and the demo site.
