### ISSUE TITLE
ec2-create-instance.sh "branch" and "repo" flags don't seem to work

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#97]
I'm on 9ff1995 and I just ran the following command:

`ec2/ec2-create-instance.sh -b 739-html-codebook -r https://github.com/lubitchv/dataverse.git`

I was trying to spin up https://github.com/IQSS/dataverse/pull/6081 to poke around with downloading codebooks as HTML.

The output suggests that the branch I wanted was deployed:

`using https://github.com/lubitchv/dataverse.git`
`building 739-html-codebook`
`using /Users/pdurbin`
`...`
`Please wait at least 15 minutes while the branch "739-html-codebook" from https://github.com/lubitchv/dataverse.git is being deployed.`
`...`
`To ssh into the new instance:`
`ssh -i /Users/pdurbin/key-pdurbin-48EE6112.pem centos@ec2-3-88-134-180.compute-1.amazonaws.com`
`Branch "739-html-codebook" from https://github.com/lubitchv/dataverse.git has been deployed to http://ec2-3-88-134-180.compute-1.amazonaws.com:8080`
`When you are done, please terminate your instance with:
aws ec2 terminate-instances --instance-ids i-021c4462979ecdd9e`

However, the tip of the "develop" branch ( https://github.com/IQSS/dataverse/commit/19b16d0 ) was deployed instead. Here's a handy link: http://ec2-3-88-134-180.compute-1.amazonaws.com

I believe that the `git clone` goes to `/tmp/`. Here's the config:

```
[root@ip-172-31-34-225 ~]# cat /tmp/dataverse/.git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/IQSS/dataverse.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "develop"]
	remote = origin
	merge = refs/heads/develop
[root@ip-172-31-34-225 ~]# 
```

**Comment by donsizemore** [comment]
I think this is fixed (sorry). Let me test a bit more.

**Comment by pdurbin** [comment]
I just spun up a new instance at http://ec2-54-92-158-217.compute-1.amazonaws.com with the same command I used before and it worked! In the bottom right corner I see "Powered by The Dataverse Project v. 4.15.1 build 739-html-codebook-2163dc6". Thanks! Closing!
